import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

public class CadastroPaciente extends javax.swing.JDialog {

    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        botaoDeConfirmar.addActionListener(e -> {
        try (Connection conn = ConexaoBancoDeDados.conectar()) {
            String sql = "INSERT INTO Pacientes (Nome, Sexo, DataDeNascimento, CPF, EstadoCivil, Codigo, Convenio, Telefone, Email, Endereco, Observacoes) "
                       + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, campoNomeCompleto.getText().trim());

            // Sexo
            String sexo = selecaoMasculino.isSelected() ? "M" : (selecaoFeminino.isSelected() ? "F" : null);
            stmt.setString(2, sexo);

            // Data de nascimento (deve estar no formato YYYY-MM-DD)
            String dataFormatada = new java.text.SimpleDateFormat("yyyy-MM-dd")
                .format(((javax.swing.JFormattedTextField.AbstractFormatter) informeDataDeNascimento.getFormatter()).stringToValue(informeDataDeNascimento.getText()));
            stmt.setString(3, dataFormatada);

            stmt.setString(4, campoCPF.getText().trim());
            stmt.setString(5, selecaoEstadoCivil.getSelectedItem().toString());
            stmt.setString(6, campoCodigo.getText().trim());
            stmt.setString(7, campoConvenio.getText().trim());
            stmt.setString(8, campoTelefone.getText().trim());
            stmt.setString(9, campoEmail.getText().trim());
            stmt.setString(10, campoEndereco.getText().trim());
            stmt.setString(11, campoObservacoes.getText().trim());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Paciente cadastrado com sucesso!");
            dispose(); // Fecha o JDialog

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar paciente:\n" + ex.getMessage());
        }
    });
        
        botaoDeCancelar.addActionListener(e -> dispose());
        
        carregarEnfermeirasNaComboBox();
        
    }
    
    private void carregarEnfermeirasNaComboBox() {
        try (Connection conn = ConexaoBancoDeDados.conectar()) {
            String sql = "SELECT Nome FROM Enfermeiras";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            selecaoEnfermeiro.removeAllItems(); // Limpa a combo box

            while (rs.next()) {
                selecaoEnfermeiro.addItem(rs.getString("Nome"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar enfermeiras:\n" + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelzinhoAzul = new javax.swing.JPanel();
        textoCadastrarNovoPaciente = new javax.swing.JLabel();
        textoNomeCompleto = new javax.swing.JLabel();
        campoNomeCompleto = new javax.swing.JTextField();
        textoSexo = new javax.swing.JLabel();
        selecaoMasculino = new javax.swing.JCheckBox();
        selecaoFeminino = new javax.swing.JCheckBox();
        informeDataDeNascimento = new javax.swing.JFormattedTextField();
        textoDataDeNascimento = new javax.swing.JLabel();
        textoCPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        textoEstadoCivil = new javax.swing.JLabel();
        selecaoEstadoCivil = new javax.swing.JComboBox<>();
        textoCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        textoConvenio = new javax.swing.JLabel();
        campoConvenio = new javax.swing.JTextField();
        textoTelefone = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        textoEmail = new javax.swing.JLabel();
        textoEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        textoObservacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoObservacoes = new javax.swing.JTextArea();
        textoEnfermeiro = new javax.swing.JLabel();
        selecaoEnfermeiro = new javax.swing.JComboBox<>();
        botaoDeConfirmar = new javax.swing.JButton();
        botaoDeCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelzinhoAzul.setBackground(new java.awt.Color(0, 255, 255));

        textoCadastrarNovoPaciente.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        textoCadastrarNovoPaciente.setText("Cadastrar Novo Paciente");

        javax.swing.GroupLayout painelzinhoAzulLayout = new javax.swing.GroupLayout(painelzinhoAzul);
        painelzinhoAzul.setLayout(painelzinhoAzulLayout);
        painelzinhoAzulLayout.setHorizontalGroup(
            painelzinhoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelzinhoAzulLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(textoCadastrarNovoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelzinhoAzulLayout.setVerticalGroup(
            painelzinhoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelzinhoAzulLayout.createSequentialGroup()
                .addComponent(textoCadastrarNovoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        textoNomeCompleto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoNomeCompleto.setText("Nome Completo:");

        campoNomeCompleto.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoSexo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoSexo.setText("Sexo:");

        selecaoMasculino.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        selecaoMasculino.setText("Masculino");

        selecaoFeminino.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        selecaoFeminino.setText("Feminino");

        informeDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        informeDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeDataDeNascimentoActionPerformed(evt);
            }
        });

        textoDataDeNascimento.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoDataDeNascimento.setText("Data de Nascimento:");

        textoCPF.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoCPF.setText("CPF:");

        campoCPF.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoEstadoCivil.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoEstadoCivil.setText("Estado Civil:");

        selecaoEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viúvo", "União Estável" }));

        textoCodigo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoCodigo.setText("Codigo:");

        campoCodigo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoConvenio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoConvenio.setText("Convênio:");

        campoConvenio.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoTelefone.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoTelefone.setText("Telefone:");

        campoTelefone.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        campoEmail.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoEmail.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoEmail.setText("E-mail:");

        textoEndereco.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoEndereco.setText("Endereço:");

        campoEndereco.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        textoObservacoes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoObservacoes.setText("Observações:");

        campoObservacoes.setColumns(20);
        campoObservacoes.setRows(5);
        jScrollPane1.setViewportView(campoObservacoes);

        textoEnfermeiro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textoEnfermeiro.setText("Enfermeiro(a):");

        selecaoEnfermeiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermeiro 1", "Enfermeiro 2", "Enfermeiro 3", "Enfermeiro 4" }));

        botaoDeConfirmar.setBackground(new java.awt.Color(51, 255, 0));
        botaoDeConfirmar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoDeConfirmar.setText("Adicionar");

        botaoDeCancelar.setBackground(new java.awt.Color(255, 51, 51));
        botaoDeCancelar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoDeCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelzinhoAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoCPF)
                            .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEstadoCivil)
                            .addComponent(selecaoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoObservacoes)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoConvenio)
                                    .addComponent(campoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoTelefone)
                                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoEndereco)
                                        .addGap(155, 155, 155))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textoEmail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botaoDeCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoDeConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoNomeCompleto)
                                        .addComponent(campoNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoSexo)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(selecaoMasculino)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(selecaoFeminino)))
                                    .addGap(101, 101, 101)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoEnfermeiro)
                                        .addComponent(selecaoEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoCodigo)
                                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textoDataDeNascimento)
                                        .addComponent(informeDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(108, 108, 108)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelzinhoAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoNomeCompleto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoSexo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(selecaoMasculino)
                                        .addComponent(selecaoFeminino))
                                    .addComponent(campoNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoEnfermeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selecaoEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selecaoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(textoDataDeNascimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(informeDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoObservacoes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoConvenio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoDeConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoDeCancelar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(textoEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informeDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informeDataDeNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroPaciente dialog = new CadastroPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeCancelar;
    private javax.swing.JButton botaoDeConfirmar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoConvenio;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNomeCompleto;
    private javax.swing.JTextArea campoObservacoes;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JFormattedTextField informeDataDeNascimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelzinhoAzul;
    private javax.swing.JComboBox<String> selecaoEnfermeiro;
    private javax.swing.JComboBox<String> selecaoEstadoCivil;
    private javax.swing.JCheckBox selecaoFeminino;
    private javax.swing.JCheckBox selecaoMasculino;
    private javax.swing.JLabel textoCPF;
    private javax.swing.JLabel textoCadastrarNovoPaciente;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoConvenio;
    private javax.swing.JLabel textoDataDeNascimento;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoEndereco;
    private javax.swing.JLabel textoEnfermeiro;
    private javax.swing.JLabel textoEstadoCivil;
    private javax.swing.JLabel textoNomeCompleto;
    private javax.swing.JLabel textoObservacoes;
    private javax.swing.JLabel textoSexo;
    private javax.swing.JLabel textoTelefone;
    // End of variables declaration//GEN-END:variables
}
