import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;  // Adicione esta linha para corrigir o erro de SQL Exception
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;



public class Painel extends javax.swing.JFrame {
    private String nomeEnfermeira;

    String dataAtual = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
    
    
    public Painel(String nomeEnfermeira) {
        this.nomeEnfermeira = nomeEnfermeira;
        initComponents();     
        
        nomeDaenfermeira.setText(nomeEnfermeira);

        atualizarNumeracaoDeAgendados();
        
        botaoAgenda.setSelected(true);
        botaoPainel.setSelected(false);
        botaoProntuarios.setSelected(false);

        
        botaoPainel.setEnabled(false);

        botaoAgenda.addActionListener(e -> {
            new Agenda(nomeEnfermeira).setVisible(true);
            dispose();
        });

        botaoProntuarios.addActionListener(e -> {
            new Prontuarios(nomeEnfermeira).setVisible(true);
            dispose();
        });
        
        botaoCadastrarPaciente.addActionListener(e -> {
            CadastroPaciente dialog = new CadastroPaciente(this, true);
            dialog.setLocationRelativeTo(this); // centraliza
            dialog.setVisible(true);

            // ✅ Recarrega a tabela após fechar o JDialog
            carregarPacientesNaTabela();
        });
        
        botaoDeslogarConta.addActionListener(e -> {
            new Login().setVisible(true); // abre a tela de login
            dispose(); // fecha a tela atual
        });


        
        carregarPacientesNaTabela();
        atualizarTabelaPacientesDoDia();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaoAgenda = new javax.swing.JToggleButton();
        botaoPainel = new javax.swing.JToggleButton();
        botaoProntuarios = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textoAtendidos = new javax.swing.JLabel();
        textoAgendados = new javax.swing.JLabel();
        textoFaltantes = new javax.swing.JLabel();
        textoConfirmados = new javax.swing.JLabel();
        NumeracaoDeConfirmados = new javax.swing.JLabel();
        NumeracaoDeFaltantes = new javax.swing.JLabel();
        NumeracaoDeAgendados = new javax.swing.JLabel();
        NumeracaoDeAtendidos = new javax.swing.JLabel();
        nomeDaenfermeira = new javax.swing.JLabel();
        botaoDeslogarConta = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPacientesDoDia = new javax.swing.JTable();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaInformeMostraPacientes = new javax.swing.JTable();
        button4 = new java.awt.Button();
        botaoCadastrarPaciente = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MoniHealth");

        botaoAgenda.setBackground(new java.awt.Color(0, 204, 255));
        botaoAgenda.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        botaoAgenda.setText("Agenda");

        botaoPainel.setBackground(new java.awt.Color(0, 204, 255));
        botaoPainel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        botaoPainel.setText("Painel");
        botaoPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPainelActionPerformed(evt);
            }
        });

        botaoProntuarios.setBackground(new java.awt.Color(0, 204, 255));
        botaoProntuarios.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        botaoProntuarios.setText("Prontuarios");

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 30)); // NOI18N
        jLabel2.setText("Pacientes do Dia");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoAtendidos.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        textoAtendidos.setForeground(new java.awt.Color(51, 204, 0));
        textoAtendidos.setText("Atendidos");

        textoAgendados.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        textoAgendados.setText("Agendados");

        textoFaltantes.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        textoFaltantes.setForeground(new java.awt.Color(255, 0, 51));
        textoFaltantes.setText("Faltantes");

        textoConfirmados.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        textoConfirmados.setForeground(new java.awt.Color(51, 51, 255));
        textoConfirmados.setText("Confirmados");

        NumeracaoDeConfirmados.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        NumeracaoDeConfirmados.setForeground(new java.awt.Color(51, 51, 255));
        NumeracaoDeConfirmados.setText("0");

        NumeracaoDeFaltantes.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        NumeracaoDeFaltantes.setForeground(new java.awt.Color(255, 0, 51));
        NumeracaoDeFaltantes.setText("0");

        NumeracaoDeAgendados.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        NumeracaoDeAgendados.setText("0");

        NumeracaoDeAtendidos.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        NumeracaoDeAtendidos.setForeground(new java.awt.Color(51, 204, 0));
        NumeracaoDeAtendidos.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(NumeracaoDeAtendidos)
                .addGap(33, 33, 33)
                .addComponent(textoAtendidos)
                .addGap(40, 40, 40)
                .addComponent(NumeracaoDeAgendados)
                .addGap(35, 35, 35)
                .addComponent(textoAgendados)
                .addGap(42, 42, 42)
                .addComponent(NumeracaoDeFaltantes)
                .addGap(18, 18, 18)
                .addComponent(textoFaltantes)
                .addGap(18, 18, 18)
                .addComponent(NumeracaoDeConfirmados)
                .addGap(39, 39, 39)
                .addComponent(textoConfirmados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NumeracaoDeConfirmados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(textoFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoConfirmados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumeracaoDeFaltantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeracaoDeAgendados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeracaoDeAtendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(textoAtendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(textoAgendados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nomeDaenfermeira.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        nomeDaenfermeira.setForeground(new java.awt.Color(51, 51, 51));
        nomeDaenfermeira.setText("Nome da Enfermeira");

        botaoDeslogarConta.setBackground(new java.awt.Color(102, 102, 102));
        botaoDeslogarConta.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        botaoDeslogarConta.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(botaoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoPainel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoProntuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomeDaenfermeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoDeslogarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoAgenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoProntuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeDaenfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoDeslogarConta))
                        .addGap(19, 19, 19)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setDividerLocation(300);

        tabelaPacientesDoDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Horario", "Paciente"
            }
        ));
        tabelaPacientesDoDia.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaPacientesDoDia);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane2.setDividerLocation(60);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel18.setText("Periodo:");

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel19.setText("Convênio:");

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel20.setText("Enfermeiro(a):");

        jComboBox16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ultimos 30 dias", "Item 2", "Item 3", "Item 4" }));

        jComboBox17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));

        jComboBox18.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setTopComponent(jPanel3);

        tabelaInformeMostraPacientes.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tabelaInformeMostraPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Data de Ultimo Agendamento", "Convênio", "Enfermeiro(a)"
            }
        ));
        tabelaInformeMostraPacientes.setGridColor(new java.awt.Color(102, 102, 102));
        tabelaInformeMostraPacientes.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaInformeMostraPacientes);

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane1.setRightComponent(jSplitPane2);

        button4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        button4.setLabel("Novo Paciente");

        botaoCadastrarPaciente.setBackground(new java.awt.Color(51, 102, 255));
        botaoCadastrarPaciente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botaoCadastrarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrarPaciente.setLabel("Cadastrar Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1449, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPainelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPainelActionPerformed


    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel("Enfermeira Teste").setVisible(true); // ✅ Exemplo para teste
            }
        });
    }
    
        private void carregarPacientesNaTabela() {
            DefaultTableModel modelo = (DefaultTableModel) tabelaInformeMostraPacientes.getModel();
            modelo.setRowCount(0); // Limpa a tabela

            String sql = """
                SELECT p.Nome, p.Telefone, p.Convenio, p.Enfermeira,
                       (
                           SELECT MAX(a.DataAgendamento)
                           FROM Agendamentos a
                           WHERE a.NomePaciente = p.Nome
                       ) AS UltimoAtendimento
                FROM Pacientes p
                ORDER BY p.Nome
            """;

            try (Connection conn = ConexaoBancoDeDados.conectar();
                 PreparedStatement stmt = conn.prepareStatement(sql);
                 ResultSet rs = stmt.executeQuery()) {

                while (rs.next()) {
                    String nome = rs.getString("Nome");
                    String telefone = rs.getString("Telefone");
                    String convenio = rs.getString("Convenio");
                    String enfermeira = rs.getString("Enfermeira");
                    String ultimoAtendimento = rs.getString("UltimoAtendimento");

                    if (ultimoAtendimento == null) {
                        ultimoAtendimento = "Sem registro";
                    }

                    modelo.addRow(new Object[]{
                        nome,
                        telefone != null ? telefone : "Sem telefone",
                        ultimoAtendimento,
                        convenio != null ? convenio : "Não informado",
                        enfermeira != null ? enfermeira : "Não atribuído"
                    });
                }

            } catch (SQLException ex) {
                System.err.println("Erro ao carregar pacientes: " + ex.getMessage());
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados dos pacientes.");
            }
        }


    
    private void atualizarNumeracaoDeAgendados() {
        // Inicialize as variáveis de contagem
        int numAgendados = 0;
        int numAtendidos = 0;
        int numFaltantes = 0;
        int numConfirmados = 0;

        // SQL para contar os agendamentos
        String sqlAgendados = "SELECT COUNT(*) FROM Agendamentos";
        String sqlAtendidos = "SELECT COUNT(*) FROM Agendamentos WHERE StatusAgendamento = 'Atendido'";
        String sqlFaltantes = "SELECT COUNT(*) FROM Agendamentos WHERE StatusAgendamento = 'Faltou'";
        String sqlConfirmados = "SELECT COUNT(*) FROM Agendamentos WHERE StatusAgendamento = 'Confirmado'";

        try (Connection conn = ConexaoBancoDeDados.conectar()) {
            // Contagem de todos os agendamentos
            try (PreparedStatement stmt = conn.prepareStatement(sqlAgendados);
                 ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    numAgendados = rs.getInt(1); // Contagem total de agendamentos
                }
            }

            // Contagem de agendamentos "Atendidos"
            try (PreparedStatement stmt = conn.prepareStatement(sqlAtendidos);
                 ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    numAtendidos = rs.getInt(1); // Contagem de "Atendidos"
                }
            }

            // Contagem de agendamentos "Faltantes"
            try (PreparedStatement stmt = conn.prepareStatement(sqlFaltantes);
                 ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    numFaltantes = rs.getInt(1); // Contagem de "Faltou"
                }
            }

            // Contagem de agendamentos "Confirmados"
            try (PreparedStatement stmt = conn.prepareStatement(sqlConfirmados);
                 ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    numConfirmados = rs.getInt(1); // Contagem de "Confirmado"
                }
            }

            // Atualiza os labels com os números contados
            NumeracaoDeAgendados.setText(String.valueOf(numAgendados));
            NumeracaoDeAtendidos.setText(String.valueOf(numAtendidos));
            NumeracaoDeFaltantes.setText(String.valueOf(numFaltantes));
            NumeracaoDeConfirmados.setText(String.valueOf(numConfirmados));

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar a quantidade de agendamentos.");
        }
    }

        public void atualizarTabelaPacientesDoDia() {
        String dataAtual = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

        try (Connection conn = ConexaoBancoDeDados.conectar()) {
            String sql = "SELECT Id, HoraAgendamento, NomePaciente, DiaDaSemana, DataAgendamento, NomeEnfermeira, TipoAgendamento, StatusAgendamento " +
                         "FROM Agendamentos " +
                         "WHERE DataAgendamento = ? " + 
                         "ORDER BY HoraAgendamento";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, dataAtual); 

            ResultSet rs = stmt.executeQuery();

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelaPacientesDoDia.getModel();
            model.setRowCount(0);  // Limpa a tabela antes de preenchê-la

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("HoraAgendamento"), 
                    rs.getString("NomePaciente")      
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar os agendamentos.");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumeracaoDeAgendados;
    private javax.swing.JLabel NumeracaoDeAtendidos;
    private javax.swing.JLabel NumeracaoDeConfirmados;
    private javax.swing.JLabel NumeracaoDeFaltantes;
    private javax.swing.JToggleButton botaoAgenda;
    private java.awt.Button botaoCadastrarPaciente;
    private javax.swing.JButton botaoDeslogarConta;
    private javax.swing.JToggleButton botaoPainel;
    private javax.swing.JToggleButton botaoProntuarios;
    private java.awt.Button button4;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel nomeDaenfermeira;
    private javax.swing.JTable tabelaInformeMostraPacientes;
    private javax.swing.JTable tabelaPacientesDoDia;
    private javax.swing.JLabel textoAgendados;
    private javax.swing.JLabel textoAtendidos;
    private javax.swing.JLabel textoConfirmados;
    private javax.swing.JLabel textoFaltantes;
    // End of variables declaration//GEN-END:variables
}
